version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: ./php
    depends_on:
      - base_mysql
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8000:80"

  base_mysql:
    container_name: base_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    restart: always
    environment:
      PMA_HOST: base_mysql
    depends_on:
      - base_mysql